name: Thomas the tank engine - Build the ESP-IDF Project

on:
  push:
  pull_request:
  merge_group:

jobs:
  build:
    strategy:
      matrix:
        idf_ver: [release-v5.0, release-v5.1, release-v5.2, release-v5.3]
        idf_target: [esp32, esp32s3, esp32c3, esp32h2]
        include:
          - idf_ver: release-v5.3
            idf_target: esp32c5
        exclude:
          - idf_ver: release-v5.0
            idf_target: esp32h2

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: ESP-IDF build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ matrix.idf_ver }}
          target: ${{ matrix.idf_target }}
